[[redirects]]
  from = "/api/*"
  to = "https://us-central1-antd-pro.cloudfunctions.net/api/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "d7c992d0-5663-4c38-a944-1f482cacdfb3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 